name: "VBAN MQTT Bridge"
version: "0.1.0"
slug: vban_mqtt
description: "MQTT ⇄ VBAN (Voicemeeter Potato) bridge"
startup: services
boot: auto
arch:
  - amd64
  - aarch64
  - armv7
  - armhf
host_network: true
options:
  mqtt_host: core-mosquitto
  mqtt_prefix: vban
schema:
  mqtt_host: str
  mqtt_prefix: str
